package net.kibotu.projecteuler.solved;

/**
 * <p>SOLVED</p>
 * <p/>
 * <p>Each new term in the Fibonacci sequence is generated by adding the
 * previous two terms. By starting with 1 and 2, the first 10 terms will
 * be:</p>
 * <p/>
 * <p>1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</p>
 * <p/>
 * <p>Find the sum of all the even-valued terms in the sequence which do
 * not exceed four million.</p>
 *
 * @author Kibotu
 * @see <a href="http://projecteuler.net/index.php?section=problems&id=2">Problem 2</a>
 */
class Problem2 {

    private Problem2() {

    }

    public static void main(String[] args) {
        System.out.println( net.kibotu.projecteuler.utils.EulerUtils.getFibonacciBigInteger(300) );
    }
}
